platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50

pipeline:
  build:
    image: ${container}
    commands:
      - VERSION=$(date +%y%m%d)
      - ./deps.sh
      - ./build.sh $VERSION
      - ./unit-test.sh
      - ./test/js/runner/run.sh

  integration:
    image: ${container}
    commands:
      - VERSION=$(date +%y%m%d)
      - NAME=platform-$VERSION-$(uname -m).tar.gz
      - ./deps.sh
      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity $NAME 89 master all ${installer} device

  upload:
    image: ${container}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - VERSION=$(date +%y%m%d)
      - ./deps.sh
      - ./upload.sh $DRONE_BRANCH $VERSION
    when:
      matrix:
        installer: sam

  ci-artifact:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./deps.sh
      - ./upload-artifact.sh integration/log $DRONE_BUILD_NUMBER/${installer}
    when:
      status: [ failure, success ] 

services:
  device:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
 
matrix:
  include:
    - platform: linux/arm
      container: armv7/armhf-debian:8
      git: syncloud/armhf-drone-git
      arch: armhf
      installer: sam
    - platform: linux/amd64
      container: debian:8
      git: plugins/git
      arch: amd64
      installer: sam
      
    - platform: linux/arm
      container: armv7/armhf-debian:8
      git: syncloud/armhf-drone-git
      arch: armhf
      installer: snapd
    - platform: linux/amd64
      container: debian:8
      git: plugins/git
      arch: amd64
      installer: snapd
