language: python
env:
  global:
    secure: DQOSdC+HawY6Ye/A715P7Dkkvt54B143FPCJ3cAZxHSljHaEHfrBYApVDiWYjEkoctahsUZz5pxmswcoy3bbrDuHdTcnPJPeW3Y6r3MwJJ3MJ6PBYsdzPp28ODl1Zssk3rZko921cZcDFQsjCMl1cPwNt0/OEFa9NRvG7Hu3sHs=
install:
- sudo $(type -P pip) install .
- pip install -r dev_requirements.txt
script:
- py.test --cov syncloud
- bash -n bin/install-java
- bash -n bin/syncloud-base-installer
- bash -n bin/syncloud-link-data.sh
- bash -n bin/syncloud-boot-installer
- bash -n bin/install-avahi
- bash -n bin/syncloud-discovery-pre-remove
deploy:
  provider: pypi
  user: syncloud-build
  password:
    secure: aLdBVYcXXDtB61PuwiAl3Sw7vxJYXSOB1xxOyYamEYkaqIVFZS6sVlQqFFHuwauEnDlZB3w4rU7GaDhIFDRXXOdEHcTf1ztiDG5GWU/hw6TDj8zUZWSkOW2HSoXzWjSbzaWtFDcBBLerMkpN6keUNZSpttM5cd8E2KG4yckeLrQ=
after_deploy:
- pip install travis-tools
- universal-version-push version syncloud/image syncloud-build GH_TOKEN master "Travis build"
- version-increment version
- universal-version-push version ${TRAVIS_REPO_SLUG} syncloud-build GH_TOKEN ${TRAVIS_BRANCH} "Travis build [skip ci]"
