language: python
env:
  global:
    secure: DQOSdC+HawY6Ye/A715P7Dkkvt54B143FPCJ3cAZxHSljHaEHfrBYApVDiWYjEkoctahsUZz5pxmswcoy3bbrDuHdTcnPJPeW3Y6r3MwJJ3MJ6PBYsdzPp28ODl1Zssk3rZko921cZcDFQsjCMl1cPwNt0/OEFa9NRvG7Hu3sHs=
install:
- pip install -e .
- pip install -r dev_requirements.txt
script:
- py.test --cov syncloud
- bash -n bin/install-java
- bash -n bin/syncloud-base-installer
deploy:
  provider: pypi
  user: syncloud-build
  password:
    secure: Up3kqeZqrAVN4Snd5J0DOC1FWvPWy96/CgLqpNbnXL24bnNdo2chrO9hMaRpLE/oIRrFgauZKp+FK5E48ZQQjzzWsB7E0ewkp1MmI5pBoeijO/c58fTQPr1X8L87wMdhIOi3dKLLVNGNlCou2huQ2YlI5xU5yevu/dLMfmdV0bY=
after_deploy:
- pip install travis-tools
- universal-version-push version syncloud/image syncloud-build GH_TOKEN master "Travis build"
- version-increment version
- universal-version-push version ${TRAVIS_REPO_SLUG} syncloud-build GH_TOKEN ${TRAVIS_BRANCH} "Travis build [skip ci]"
