name: syncloud-platform
summary: Syncloud Platform
description: Syncloud service store.
grade: stable
confinement: strict

apps:
  configure:
    command: bin/snap-configure
  uwsgi-public:
    command: uwsgi/bin/uwsgi --ini ${SNAP_COMMON}/config/uwsgi/public.ini
    daemon: notify
    restart-condition: always
    plugs: [network, network-bind]
  uwsgi-internal:
    command: uwsgi/bin/uwsgi --ini ${SNAP_COMMON}/config/uwsgi/internal.ini
    daemon: notify
    restart-condition: always
    plugs: [network, network-bind]
  openldap:
    command: openldap/libexec/slapd -h ldap://127.0.0.1:389 -F ${SNAP_COMMON}/slapd.d
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind]
  nginx:
    command: nginx/sbin/nginx -c ${SNAP_COMMON}/config/nginx/nginx.conf
    stop-command: nginx/sbin/nginx -c ${SNAP_COMMON}/config/nginx/nginx.conf -s stop
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind]
parts: 
  platform:
    plugin: dump
    source: ../build/platform

