name: syncloud-platform
version: 16.11
summary: Syncloud Platform
description: Syncloud service store.
grade: stable
confinement: strict

apps:
  configure:
    command: bin/snap-configure
  #nginx:
    #command: nginx/sbin/nginx -c $SNAP/config/nginx/nginx.conf
    #stop-command: nginx/sbin/nginx -c $SNAP/config/nginx/nginx.conf -s stop
    #daemon: forking
    #restart-condition: always
    #plugs: [network, network-bind]
  #uwsgi:
    #command: uwsgi/bin/uwsgi --ini $SNAP/config/uwsgi/public.ini
    #daemon: simple
    #restart-condition: always
    #plugs: [network, network-bind]
  #openldap:
   # command: openldap/libexec/slapd -h "ldap:/// ldapi:///" -F $SNAP_COMMON/slapd.d
   # daemon: forking
   # restart-condition: always
   # plugs: [network, network-bind]

hooks:
  configure: configure

parts: 
  nginx:
    plugin: dump
    source: ../build/platform/nginx
    organize:
      '*': nginx/

  uwsgi:
    plugin: dump
    source: ../build/platform/uwsgi
    organize:
      '*': uwsgi/

  openldap:
    plugin: dump
    source: ../build/platform/openldap
    organize:
      '*': openldap/

  openssl:
    plugin: dump
    source: ../build/platform//openssl
    organize:
      '*': openssl/

  python:
    plugin: dump
    source: ../build/platform/python
    organize:
      '*': python/

  platform-bin:
    plugin: dump
    source: ../build/platform/bin
    organize:
      '*': bin/

  platform-config:
    plugin: dump
    source: ../build/platform/config.templates 
    organize:
      '*': config.templates/

  platform-www:
    plugin: dump
    source: ../build/platform/www
    organize:
      '*': www/

